version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # volumes:
    #   - ./ssl:/etc/ssl
    #   - ./nginx.conf:/etc/nginx/nginx.conf

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # volumes:
    #   - ./ssl:/etc/ssl
    #   - ./nginx.conf:/etc/nginx/nginx.conf

  proxy:
    image: nginx
    volumes:
      - /etc/ssl:/etc/ssl
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
